
services:
  backend:
    build: ./auction-backend
    env_file:
      - ./auction-backend/.env
    # depends_on:
    #   - serviceName
    ports: 
      - "8000:8000"
    volumes:
      - ./auction-backend:/app
    environment:
      - DATABASE_URL=value
    
  frontend:
    build: ./auction-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./auction-frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_API_URL=http://localhost:8000